version: '2'
services:
  gtm_m_1:
    build:
      context: .
      dockerfile: Dockerfile.gtm.Dockerfile
    networks:
      - postgres-cluster
  gtm_p_1:
    build:
      context: .
      dockerfile: Dockerfile.gtm-proxy.Dockerfile
    networks:
      - postgres-cluster
  coord_m_1:
    build:
      context: .
      dockerfile: Dockerfile.coord.Dockerfile
    networks:
      - postgres
      - postgres-cluster
  data_m_1:
    build:
      context: .
      dockerfile: Dockerfile.data.Dockerfile
    networks:
      - postgres-cluster
  coord_m_2:
    extends: coord_m_1
    environment:
      - PG_COORD_NODE=coord_m_2
  data_m_2:
    extends: data_m_1
    environment:
      - PG_DATA_NODE=data_m_2
networks:
  postgres: {}
  postgres-cluster:
    internal: true
