version: '2'
services:
  gtm_m_1:
    build:
      context: .
      dockerfile: Dockerfile.gtm.Dockerfile
    networks:
      - postgres-b
  gtm_p_1:
    environment:
      - PG_GTM_HOST=gtm_m_1
    build:
      context: .
      dockerfile: Dockerfile.gtm-proxy.Dockerfile
    networks:
      - postgres-b
  coord_m_1:
    build:
      context: .
      dockerfile: Dockerfile.coord.Dockerfile
    networks:
      - postgres
      - postgres-b
networks:
  postgres:
    external:
      name: postgres
  postgres-b:
    external:
      name: postgres-b
