platform: linux
image_resource:
  type: docker-image
  source:
    repository: concourse/buildroot
    tag: git
inputs:
  - name: src
outputs:
  - name: meta
run:
  path: sh
  args:
    - -ce
    - |
      meta=$PWD/meta
      cd src
      git describe | tr -d '\n' > $meta/version
      cat $meta/*
