platform: linux
inputs:
  - name: meta
outputs:
  - name: pkg
run:
  user: root
  path: sh
  args:
    - -ce
    - |
      src=/var/lib/postgresql
      lib=/usr/local/lib/postgresql
      ci=$src/ci
      pkg=$PWD/pkg
      
      cp $ci/* $pkg
      cp -R $lib $pkg/lib/
      
      ls -AlhR $pkg
